batch_size: 1
model_name: model_name
output_file: path_to_output_file
res_file: path_to_result_file
prompt_file: path_to_retrieved_demonstration_file
max_length: 2048 # max length of tokenizer
generate_max_len: 100
n_tokens: 2048 # max length of (prompt + task input+ task output)
task_name: task_name
prompt_pool_path: path_to_prompt_pool_file
num_prompts: 3
random_sample: False
cache_dir: path_to_cache_dir
random_seed: 42
train_clusters: 

method: mdr

dataset_reader:
  _target_: src.dataset_readers.few_shot_dsr.FewShotDatasetReader
  model_name: ${model_name}
  task_name: ${task_name} 
  prompt_file: ${prompt_file}
  prompt_pool_path: ${prompt_pool_path}
  num_prompts: ${num_prompts}
  n_tokens: ${n_tokens}
  random_sample: ${random_sample}
  random_seed: ${random_seed}
  cache_dir: ${cache_dir}
  max_length: ${max_length}
  train_clusters: ${train_clusters}

hydra:
  run:
    dir: path_to_experiment_dir